// <auto-generated />
namespace OperationLog.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropNetworkNameTableDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropNetworkNameTableDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201606080827534_Drop.NetworkName.TableDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
